### PR TITLE
add support for http proxy

### PR DESCRIPTION
**Pull request by zhaoxy2850**
I have the same problem in this issue.
https://github.com/sideshow/apns2/issues/24#issuecomment-302920438
I found that apns2 doesn't support http2 proxy. In order to fix the problem, I made some improvements to the following code.

### CODE REVIEW

**Comment by deltapath-eric** [comment]
Hi, seem this changes only available in cert client and the token client is kind of missing?

**Comment by emiksk** [comment]
Will this PR be merged?
I wish this feature is implemented to the library.

**Comment by emiksk** [comment]
Hi, @sideshow 

I want to add this feature in this library.
What do I should do to merge this pull request or add this feature?

**Comment by sideshow** [comment]
@zhaoxy2850 @emiksk 

I agree that there is definitely a need for apns2 to support proxy servers but I am hesitant to merge this as it is because of the following;

2) Its adds two more methods `NewProxyClient` and `NewProxyTokenClient` so now we have 4 client constructors. I think a better way is to allow either setting a default Transport/Httpclient or allowing you to pass a custom one into the constructor as i am sure there will be more customisations that others want to do to the transport/httpclient and this will avoid us having to add more methods each time.

1) This uses `http2.ConfigureTransport` which takes a http1 connection and upgrades it to http2 whereas the other methods used a pure http2 connection. I would rather use the http2 transport directly however the http2 transport doesn't yet support http2 proxying.

For now I have added an example of how to use the proxy code you have in this PR with master as it is today; Its a little bit more code to get set up but it does work and means you can use with a proxy. Please try [this](https://github.com/sideshow/apns2/pull/158/files)  and let me know how you get on. Thanks

**Comment by zhaoxy2850** [comment]
Thanks. This can be an alternative way until http2 transport support http2 proxying.

**Comment by emiksk** [comment]
@sideshow 
Thank you so much for your explanation and support.
I understand your opinion. I'll follow the example!

**Pull request closed without merging**
