### PR TITLE
Add support for the apns-push-type header

### LINKED ISSUE #137: iOS 13 feature support
apns-push-type  https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns#2947610

### PR DESCRIPTION
**Pull request by wiggisser**
fixes #137

### CODE REVIEW

**Comment by benguild** [comment]
Curious if we're planning to merge this or #138? Trying to test something with iOS 13 now.

Would be great to get either into `master`.

**Comment by froodian** [comment]
Same here - @sideshow do you think this pull is mergable? 🙏

**Comment by sideshow** [comment]
Hey @wiggisser thanks for the PR, this looks great. 

I would like to merge this but any change you could rebase of master? - this should fix the tests. 

Once i've done a smoke test on ios12 and 13 I will merge.

Thanks again!

**Comment by wiggisser** [comment]
@sideshow I did a rebase on the latest master from the upstream repository, but I'm not sure about what to do with the failing checks ...

**Comment by benguild** [comment]
@sideshow Would be awesome to merge this week 👍🏻

**Comment by adamcodes** [comment]
Howdy folks. I've inherited a service at my company that uses this library and I'm getting some pressure to add support for `apns-push-type` ahead of the iOS 13 release. Would friendly encouragement or a bribe help get this PR completed and merged? 🙇

**Comment by adamcodes** [comment]
It looks like the build may have failed due to a temporary network request issue. Could someone with write access rerun travis-ci? `On the build's detail screen, there is a button ↻ with the tooltip "Restart Build".`

**Comment by sideshow** [comment]
Thanks again for this PR, Tests are now passing and I have smoke tested on iOS 13 beta. It looks like apple aren't yet enforcing the requirement for this header on the iOS 13 beta. PR works with these headers but it also works without it.

**Pull request merged**
