### PR TITLE
ClientManager

### PR DESCRIPTION
**Pull request by dwieeb**
Here's an implementation of a potential client pool for this library. The request originated from https://github.com/sideshow/apns2/issues/21. It has a few features one might expect in a pool, such as a maximum size and age (both of which can be disabled), as well as a way to create clients automatically if not found in the pool. Clients are looked up by doing a sha1 hash of the credential's bytes.

Implementation is basically a LRU cache with an optional time constraint. Lookups are O(1) using a map. LRU is achieved with a doubly linked list. These data structures are not thread safe, but the implementation should be thread safe as a simple mutex is wrapped around each potentially unsafe method.

I have not used this version in production. I wanted to submit this early to open discussion. What are some likes/dislikes, etc.

@sideshow @c3mb0 @nordicdyno

Credit to bradfitz: https://github.com/golang/groupcache/blob/master/lru/lru.go

### CODE REVIEW

**Comment by dwieeb** [comment]
I don't think the Go 1.4.3 failure in Travis is my doing, but I could be wrong.

**Comment by sideshow** [comment]
Thanks for the pull request @dwieeb 
Looks pretty cool, I will have a play with this tomorrow

**Comment by dwieeb** [comment]
@sideshow You're welcome. Does everything look good?

**Comment by alphapigger** [comment]
Behaviors of `pool` more like `session` . It  support multiple application, but one application only hold one tcp connection@dwieeb

**Comment by dwieeb** [comment]
@alphapigger Right, it's not a "connection" pool one would be used to. What would a better name be? `ClientSessionManager`, `ClientManager`?

**Comment by alphapigger** [comment]
`ClientSessionManager, ClientManager`  is all ok,I just want to make sure the code that match up the point. @dwieeb

**Comment by dwieeb** [comment]
Okay, that's renamed. All ready.

**Comment by NeoCN** [comment]
Is there any update on this？

**Comment by sideshow** [comment]
@dwieeb Sorry for the delay on reviewing this. We are doing something very similar in an internal project which is used in production, so my way of testing this was to try swapping out our current implementation for yours which looks superior. I think this will be an awesome addition to the library. Thanks again an will try and review shortly.

**Comment by dwieeb** [comment]
@sideshow Great to hear! I look forward to pulling this in.

**Comment by dwieeb** [comment]
@sideshow Have you had time to review it again? Really looking forward to having this in the library.

**Comment by nordicdyno** [comment]
Is only me seeing the problem with potential connection leaking (after eviction) in this code?

**Comment by sideshow** [comment]
Hey @dwieeb We are currently trying to merge into a large project to test.

**Comment by sideshow** [comment]
@nordicdyno can you be more specific. Thanks

**Comment by nordicdyno** [comment]
@sideshow There is no explicit disconnection before ```m.removeElement(ele)```. So I aware that system sockets could be held by connections what are already removed from user space.

**Comment by sideshow** [comment]
@nordicdyno I ran some tests and this does leak/hold connections open after they are removed from the ConnectionManager. We need some kind of explicit CloseConnections method on the client which we can cll before removing them. @dwieeb with the exception of this, it been tested and is ready to merge. I just want to fix this before I merge in (any help appreciated). Thanks again  for the code!

**Comment by dwieeb** [comment]
@nordicdyno @sideshow To me, this is normal behavior. See https://golang.org/src/net/http/transport.go#L54

>     57	// By default, Transport caches connections for future re-use.
>     58	// This may leave many open connections when accessing many hosts.
>     59	// This behavior can be managed using Transport's CloseIdleConnections method
>     60	// and the MaxIdleConnsPerHost and DisableKeepAlives fields.

I believe this PR has merely revealed a larger issue with this library, in that anyone who is "accessing many hosts" (by creating many Clients) will have connections left open. I also believe this is fine (it is the normal behavior of the http go libs). 

If we want to address this, we can provide configuration options for `http2.Transport` (https://github.com/sideshow/apns2/blob/master/client.go#L60-L65), but the fine-tuning of this I believe should be left on the library consumer.

**Comment by sideshow** [comment]
@dwieeb "I believe this PR has merely revealed a larger issue with this library" Agree with this. I will go ahead and merge and we can address this as a seperate issue. Thanks again for the PR!

**Pull request merged**
