### PR TITLE
Support pushtotalk type push notification

### PR DESCRIPTION
**Pull request by deltapath-eric**
Hi

First of all thanks for the effort on this great library.

Currently i have some usage on push to talk which required the push type of pushtotalk.
it would be great if you can merge the following changes.

Thanks!
Eric

### CODE REVIEW

**Comment by deltapath-eric** [comment]
Hi @sideshow 

is there any chance that you can help to review and merge with release on this change set?
Thank you for your time!

Eric

**Comment by deltapath-eric** [comment]
further updated the changes to sync with master
thanks!

**Review by sideshow — APPROVED** [review]

**Comment by sideshow** [comment]
Thanks for the PR @deltapath-eric

**Comment by deltapath-eric** [comment]
Thanks for merging, hope we can have a new release soon!

**Pull request merged**
