### PR TITLE
Allow PKCS#8 private keys in .pem files

### PR DESCRIPTION
**Pull request by jameshfisher**

### CODE REVIEW

**Comment by jameshfisher** [comment]
This should fix https://github.com/sideshow/apns2/issues/100

**Comment by jameshfisher** [comment]
To add some more context, we use sideshow/apns2 internally at Pusher, and we've experienced issues with some customers' `openssl` versions generating `.pem` files with PKCS#8 private keys. https://github.com/pusher/libPusher/issues/257

**Comment by jameshfisher** [comment]
@sideshow WDYT?

**Comment by SimpleApp** [comment]
@sideshow Is there something wrong with that pull request ?

**Comment by sideshow** [comment]
Sorry @jameshfisher @SimpleApp for not taking a look at this sooner.
It looks awesome, thanks so much for the contribution! 

I had seen this problem before with different versions of open SSL. Can you guys confirm exactly which version you are running? Looking forward to merging this.

**Comment by jameshfisher** [comment]
@sideshow I've seen it with at least two different versions of OpenSSL:

```
$ openssl version  # MacOS, which uses the LibreSSL fork
LibreSSL 2.2.7
```

```
$ openssl version  # on Ubuntu 14.04
OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by SimpleApp** [comment]
@sideshow Same here, used LibreSSL 2.2.7 (mac OS High Sierra 10.13.1)

**Comment by sideshow** [comment]
Thanks for the PR :)

**Comment by jameshfisher** [comment]
thanks! :)

**Pull request merged**
