### PR TITLE
Go modules support

### PR DESCRIPTION
**Pull request by jbendotnet**
- Add go.mod
- Update vendored dependencies to include all dependent modules

### CODE REVIEW

**Comment by jbendotnet** [comment]
Hi @sideshow, this PR adds support for Go modules and vendors all dependencies, including those used in testing. This has required a change to the supported Go versions, as some dependencies were updated as part of that process. Hope useful, thanks.

**Comment by jdottori** [comment]
Hi @sideshow, would you like to merge this? I've seen several forks doing something similar and updating JWT dependency because of a DependaBot update. I can open a ticket to discuss the best approach there with a comparison of the existing ones.

**Comment by eljoth** [comment]
Hey @jdottori I was just about to open the same PR and saw yours in the last moment!
@sideshow are there any updates on this? Really would appreciate go mod support.

**Comment by sideshow** [comment]
Thanks for this PR! @jbendotnet 
I'll update the JWT dependency and bump the go version in a seperate PR @jdottori @eljoth

**Pull request merged**
